version: '3.8'

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@db:27017

  redis:
    image: redis
    ports: 
      - 6379:6379
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-enterprise-kafka:7.0.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991

  envoy:
    image: envoyproxy/envoy:v1.21-latest
    restart: always
    ports:
      - "8099:8099"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: /usr/local/bin/envoy -l info -c /etc/envoy/envoy.yaml

  email-service:
    image: services-email
    restart: always

volumes:
  db:
